sudo: false
language: c
os:
  - linux
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libsdl1.2-dev
before_script:
  - set -x
  - set -e
  - export PATH=$(pwd)/bin:$PATH
script:
  - git clone --depth 1 https://github.com/nim-lang/csources.git
  - cd csources
  - sh build.sh
  - cd ..
  - ./bin/nim c koch
  - ./koch boot
  - ./koch boot -d:release
  - ./koch test help || true
  - echo lib types typerel metatype generics macros template vm stdlib array tuples | xargs -n1 -P$(nproc) tests/testament/tester c
