sudo: false
language: c
os:
  - linux
  - osx
dist: trusty


matrix:
  allow_failures:
    - os: osx

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libsdl1.2-dev
    - libgc-dev
    - libsfml-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install boehmgc; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sfml; fi

before_script:
  - |
    if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
      TRAVIS_COMMIT_RANGE="FETCH_HEAD...$TRAVIS_BRANCH"
    fi
    git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(\.md$)|(\.txt$)(\.rst)|(^(doc|icons|web|))/' || {
      echo "Only the docs were updated, the tests will not run."
      export SKIPTESTS="true"
    }
  - set -e
  - git clone --depth 1 https://github.com/nim-lang/csources.git
  - cd csources
  - sh build.sh
  - cd ..
  - sed -i -e 's,cc = gcc,cc = clang,' config/nim.cfg
  - export PATH=$(pwd)/bin${PATH:+:$PATH}
script:
  - nim c koch
  - ./koch boot
  - ./koch boot -d:release
  - |
    if [ "$SKIPTESTS" != "true" ]; then
      ./koch nimble
      nim e tests/test_nimscript.nims
      nimble install zip -y
      nimble install opengl
      nimble install sdl1
      nimble install jester@#head
      nimble install niminst
      nim c --taintMode:on -d:nimCoroutines tests/testament/tester
      tests/testament/tester --pedantic all -d:nimCoroutines
      ./koch csource
      ./koch nimsuggest
    fi
  - ./koch web
#  - nim c -r nimsuggest/tester
  - ( ! grep -F '.. code-block' -l -r --include '*.html' --exclude contributing.html --exclude docgen.html --exclude tut2.html )
  - ( ! grep -F '..code-block' -l -r --include '*.html' --exclude contributing.html --exclude docgen.html --exclude tut2.html )
