image: freebsd/latest
packages:
- databases/sqlite3
- devel/boehm-gc
- devel/boehm-gc-threaded
- devel/pcre
- devel/sdl20
- devel/sfml
- www/node
sources:
- https://github.com/nim-lang/Nim
environment:
  CC: /usr/bin/clang
tasks:
- setup: |
    cd Nim
    git clone --depth 1 -q https://github.com/nim-lang/csources.git
    cd csources
    sh build.sh
    cd ../
    bin/nim c --skipUserCfg --skipParentCfg koch
    sed -i'.original' -e 's/cc = gcc/cc = clang/g' config/nim.cfg
    echo 'export PATH=$HOME/Nim/bin:$PATH' >> $HOME/.buildenv
- test: |
    cd Nim
    ./koch runCI && exitcode=$? || exitcode=$?
    if [[ $exitcode -ne 0 ]]; then
      nim c -r tools/ci_testresults.nim
    fi

    exit $exitcode
triggers:
- action: email
  condition: failure
  to: Andreas Rumpf <rumpf_a@web.de>
