# see https://man.sr.ht/builds.sr.ht/compatibility.md#freebsd
image: freebsd/latest
# image: freebsd/11.x # workaround https://github.com/timotheecour/Nim/issues/76

packages:
- databases/sqlite3
# - devel/boehm-gc-threaded
- devel/pcre
- devel/sdl20
- devel/sfml
- www/node
- devel/gmake
- devel/git
sources:
- https://github.com/nim-lang/Nim
environment:
  CC: /usr/bin/clang
tasks:
- setup: |
    # sudo needed
    sudo pkg update -q -f
    sudo pkg install -q devel/boehm-gc-threaded

    echo "D20200327T203132.3"
    cd Nim
    git clone --depth 1 -q https://github.com/nim-lang/csources.git
    gmake -C csources -j $(sysctl -n hw.ncpu)
    bin/nim c --skipUserCfg --skipParentCfg koch
    echo 'export PATH=$HOME/Nim/bin:$PATH' >> $HOME/.buildenv
- test: |
    cd Nim
    if ! ./koch runCI; then
      nim c -r tools/ci_testresults.nim
      exit 1
    fi
triggers:
- action: email
  condition: failure
  to: Andreas Rumpf <rumpf_a@web.de>
