name:        "Bug Report"
description: "Create a new bug report. Have you found an unexpected behavior?, use this form."
title:       "Think about the title, twice."
labels:      ["unconfirmed"]
body:

- type: markdown
  attributes:
    value: |
      - **Please provide a minimal code example that reproduces the Bug!.** :bug:
        Reports with full repro code and descriptive detailed information will likely receive fixes faster.

- type: dropdown
  id: architecture
  attributes:
    label: Architecture
    description: What is your Hardware Architecture?.
    options:
      - x86_64 (Default)
      - x86_32 (32Bit)
      - ARM_64 (64Bit)
      - ARM_32 (32Bit)
      - AVR, Arduino, ESP32
      - RISC (RISC-V)
      - Others (Unknown)
  validations:
    required: false

- type: dropdown
  id: os
  attributes:
    label: Operating System
    description: What is your Operating System?.
    options:
      - Linux
      - Windows
      - Mac OSX
      - Android
      - BSD
      - FreeDOS
      - ReactOS
      - Others (Unknown)
  validations:
    required: false

- type: dropdown
  id: disk
  attributes:
    label: Disk
    description: What is your main Disk Storage?.
    options:
      - SSD (Solid, M2, MSATA, NVME)
      - HDD (SATA, IDE, SCSI, Mechanical)
      - USB (Flash, USB2, USB3)
      - Diskless (Netboot, run from RAM)
      - Others (Unknown)
  validations:
    required: false

- type: dropdown
  id: ram
  attributes:
    label: Memory
    description: What is your total RAM Memory capacity?.
    options:
      - 1 Gigabyte
      - 2 Gigabytes
      - 4 Gigabytes
      - 8 Gigabytes
      - 16 Gigabytes
      - 32 Gigabytes
      - 64 Gigabytes
      - 128 Gigabytes
      - 256 Gigabytes
      - 512 Gigabytes
      - Less than 1 Gigabyte
      - Others (Unknown)
  validations:
    required: false

- type: dropdown
  id: cores
  attributes:
    label: CPU Cores
    description: What is your total CPU Cores count?.
    options:
      - 1 CPU Cores
      - 2 CPU Cores
      - 4 CPU Cores
      - 8 CPU Cores
      - 16 CPU Cores
      - 32 CPU Cores
      - 64 CPU Cores
      - 128 CPU Cores
      - 256 CPU Cores
      - 512 CPU Cores
      - Others (Unknown)
  validations:
    required: false

- type: dropdown
  id: internet
  attributes:
    label: Internet Connection
    description: What is your Internet connection?.
    options:
      - Optical Fiber (very fast)
      - DSL (aDSL, DSL, etc)
      - Wifi (WLAN, Wireless)
      - LAN (RJ45, Local, etc)
      - Satellite (StarLink, etc)
      - Mobile (4G, 3G, Edge, etc)
      - Offline (No Internet)
      - Others (Unknown)
  validations:
    required: false

- type: dropdown
  id: browser
  attributes:
    label: What is your web browser?
    options:
      - Chrome/Chromium
      - Firefox/Firefox Fork
      - Apple Safari
      - Microsoft Edge
      - KDE (Konqueror, Falkon, QtWebkit, etc)
      - Microsoft Internet Explorer (Deprecated)
      - Others (Unknown)
  validations:
    required: false

- type: dropdown
  id: device
  attributes:
    label: Device
    description: What kind of computer is it?.
    options:
      - Desktop PC
      - Server PC
      - Mobile device (Smartphone, Smartwatch, Tablet)
      - Docker/Qemu (Container)
      - VirtualBox/Vagrant (Virtual Machine)
      - Embedded/IOT
      - Arduino Kit/ESP32 Kit
      - Game Console (Playstation, XBOX, SteamDeck, Switch)
      - SmartTV/SmartDisplay/Smartprojector
      - Drone/Robot/Exoskeleton
      - ASIC/FPGA/Crypto-mining hardware
      - PLC/Industrial/heavy machine
      - Point Of Sale/Kiosk/ATM
      - Car/Self-Driving/On-Board Computer
      - Electric scooter/Electric bike
      - Satellite/MicroSatellite
      - Military machine
      - Others (Unknown)
  validations:
    required: false

- type: textarea
  id: what-happened
  attributes:
    label: What happened?
    description: |
      Use DETAILED DESCRIPTIVE information about the problem.
      Here, you go into more details about your Bug report. This section can be a few paragraphs long.
    placeholder: Bug reports with full repro code and detailed information will be fixed faster.
  validations:
    required: true

- type: textarea
  id: current-logs
  attributes:
    label: Current Standard Output Logs
    description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
    placeholder: Bug reports with full repro code and detailed information will be fixed faster.
    render: shell

- type: textarea
  id: expected-logs
  attributes:
    label: Expected Standard Output Logs
    description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
    placeholder: Bug reports with full repro code and detailed information will be fixed faster.
    render: shell

- type: textarea
  id: possible-solution
  attributes:
    label: Possible Solution
    description: Propose a possible solution.
  validations:
    required: false

- type: textarea
  id: extra-info
  attributes:
    label: Additional Information
    description: Any additional relevant information.
  validations:
    required: false

- type: textarea
  id: incompatibility
  attributes:
    label: Backwards Compatibility
    description: If your Bug Report introduces backward-incompatible changes, describe them and propose how to deal with them.
  validations:
    required: false

- type: markdown
  attributes:
    value: |
      - Thanks for your contributions!, your Bug report will receive feedback from the community soon...
      - **Remember to :star: Star the Nim project on GitHub!.**
      - Please check whether the problem still exists in git devel branch, see [rebuilding the compiler](https://nim-lang.github.io/Nim/intern.html#rebuilding-the-compiler).
      - Consider writing a PR targetting devel branch after filing this, see [contributing](https://nim-lang.github.io/Nim/contributing.html).
      - If it's a pre-existing compiler bug, see [Debugging the compiler](https://nim-lang.github.io/Nim/intern.html#debugging-the-compiler)
        which should give more context on a compiler crash.
      - If it's a regression, you can help us by identifying which version introduced the bug,
        see [Bisecting for regressions](https://nim-lang.github.io/Nim/intern.html#bisecting-for-regressions),
        or at least try known past releases (eg `choosenim 1.2.0`).
      - [Please, consider a Donation for the Nim project.](https://nim-lang.org/donate.html)
