name: Nim Docs CI
on:
  push:
    # Run only on changes on these files
    paths:
      - 'lib/**.nim'
      - 'doc/**.rst'
      - 'doc/nimdoc.css'

  pull_request:
    # Run only on changes on these files
    paths:
      - 'lib/**.nim'
      - 'doc/**.rst'

jobs:
  build:
    name: 'Docs builder'
    runs-on: ubuntu-18.04
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Checkout csources'
        uses: actions/checkout@v2
        with:
          repository: nim-lang/csources
          path: csources

      - name: 'Add build binaries to PATH'
        shell: bash
        run: echo "::add-path::${{ github.workspace }}/bin"

      - name: 'Build 1-stage compiler from csources'
        shell: bash
        run: |
          ncpu=$(nproc)
          [[ -z "$ncpu" || $ncpu -le 0 ]] && ncpu=1

          make -C csources -j $ncpu CC=gcc

      - name: 'Build koch'
        shell: bash
        run: nim c koch

      - name: 'Build the real compiler'
        shell: bash
        run: ./koch boot

      - name: 'Build documentation'
        shell: bash
        run: ./koch doc

      - name: 'Prepare documentation for deployment'
        if: github.event_name == 'push' && github.ref == 'devel'
        shell: bash
        run: cp -f doc/html/{overview,index}.html

      - name: 'Publish documentation to Github Pages'
        if: github.event_name == 'push' && github.ref == 'devel'
        uses: crazy-max/ghaction-github-pages@v1
        with:
          build-dir: doc/html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
